#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v21
# autospec commit: e36a856
#
Name     : fio
Version  : 3.39
Release  : 71
URL      : https://github.com/axboe/fio/archive/fio-3.39/fio-3.39.tar.gz
Source0  : https://github.com/axboe/fio/archive/fio-3.39/fio-3.39.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: fio-bin = %{version}-%{release}
Requires: fio-data = %{version}-%{release}
Requires: fio-license = %{version}-%{release}
Requires: fio-man = %{version}-%{release}
BuildRequires : bison
BuildRequires : buildreq-configure
BuildRequires : flex
BuildRequires : libaio-dev
BuildRequires : numactl-dev
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: build.patch

%description
Overview and history
--------------------
Fio was originally written to save me the hassle of writing special test case
programs when I wanted to test a specific workload, either for performance
reasons or to find/reproduce a bug. The process of writing such a test app can
be tiresome, especially if you have to do it often.  Hence I needed a tool that
would be able to simulate a given I/O workload without resorting to writing a
tailored test case again and again.

%package bin
Summary: bin components for the fio package.
Group: Binaries
Requires: fio-data = %{version}-%{release}
Requires: fio-license = %{version}-%{release}

%description bin
bin components for the fio package.


%package data
Summary: data components for the fio package.
Group: Data

%description data
data components for the fio package.


%package extras
Summary: extras components for the fio package.
Group: Default

%description extras
extras components for the fio package.


%package license
Summary: license components for the fio package.
Group: Default

%description license
license components for the fio package.


%package man
Summary: man components for the fio package.
Group: Default

%description man
man components for the fio package.


%prep
%setup -q -n fio-fio-3.39
cd %{_builddir}/fio-fio-3.39
%patch -P 1 -p1
pushd ..
cp -a fio-fio-3.39 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1739900719
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static ; \
./configure --disable-native --extra-cflags="$CFLAGS"
make  %{?_smp_mflags}  V=1

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static ; \
./configure --disable-native --extra-cflags="$CFLAGS"
make  %{?_smp_mflags}  V=1
popd
%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1739900719
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/fio
cp %{_builddir}/fio-fio-%{version}/COPYING %{buildroot}/usr/share/package-licenses/fio/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/fio-fio-%{version}/MORAL-LICENSE %{buildroot}/usr/share/package-licenses/fio/ffb3881ef6e7ef966b9fce711e1596d92a0e1e58 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/fio
/V3/usr/bin/fio-btrace2fio
/V3/usr/bin/fio-dedupe
/V3/usr/bin/fio-genzipf
/V3/usr/bin/fio-verify-state
/usr/bin/fio
/usr/bin/fio-btrace2fio
/usr/bin/fio-dedupe
/usr/bin/fio-genzipf
/usr/bin/fio-histo-log-pctiles.py
/usr/bin/fio-verify-state
/usr/bin/fio_generate_plots
/usr/bin/genfio

%files data
%defattr(-,root,root,-)
/usr/share/fio/graph2D.gpm
/usr/share/fio/graph3D.gpm
/usr/share/fio/math.gpm

%files extras
%defattr(-,root,root,-)
/usr/bin/fio2gnuplot
/usr/bin/fio_jsonplus_clat2csv
/usr/bin/fiologparser.py
/usr/bin/fiologparser_hist.py

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/fio/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/fio/ffb3881ef6e7ef966b9fce711e1596d92a0e1e58

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/fio.1
/usr/share/man/man1/fio2gnuplot.1
/usr/share/man/man1/fio_generate_plots.1
/usr/share/man/man1/fiologparser_hist.py.1
